### ISSUE TITLE
ボードのカテゴリ管理

### ISSUE THREAD

**Issue by takumaki** [ntechlab/KPT-board#15]
ボードを選択する前にカテゴリで絞り込みたい。

**Comment by tnog2014** [comment]
ボードの作成時にカテゴリを設定できるようにしました。
カテゴリは既存のカテゴリの中から選択、もしくは、新規作成できます。
ボード情報編集画面で変更することも可能です。

**Comment by takumaki** [comment]
確認しました～！
いいですね！

**Comment by takumaki** [comment]
対応完了につきクローズします。

**Comment by takumaki** [comment]
対応完了につきクローズします。
