### ISSUE TITLE
画像のアップロード機能

### ISSUE THREAD

**Issue by tnog2014** [ntechlab/KPT-board#5]
ボード情報変更画面から背景画像のアップロードや削除をできるようにする。

**Comment by takumaki** [comment]
ありがとうございます！早速試したところ、１つ問題が。。汗
確かにアップロードできるのですが、画像が表示されない？ようです。
もしや・・・と思い、プロセスを再起動すると画像が反映されました。
画像の格納場所を変えたら何とかなるものでしょうか・・・？

**Comment by tnog2014** [comment]
ファイルアップロード時にsailsサーバーがフリーズしますか？
フリーズする現象が発生したことがあります。こちらの原因は調査中です。
開発は、Windowsで行っているのですが、Linuxの場合、何かがおかしくなる？軽く調べてみます。

**Comment by takumaki** [comment]
アップロードしたファイルを参照しようとして、getで404が出てますね。
こんなパスです→～/images/background/xxx.png
このパスは、プロセスの再起動をしないとsailsにロードされないのではないかという感じがします。。
パーミッションを見てみましたが、ほかのファイルと一緒でした。

あと、関係ないですが、「js/underscore-min.map 」も404が出ているようです。
ただ、特段動きには影響なさそうです。

**Comment by tnog2014** [comment]
起動モードによる動きの違いかもしれません。
今まで、開発モードで起動して動作確認していたのですが、プロダクションモード(--prod指定あり)の場合、ファイルのキャッシュの動きが少し変わります。プロダクションモードの場合、起動時にassets内の画像ファイルを.tmp内の対応箇所にコピーして、サーバーからはその場所を見ている可能性がありますね。だとすると、アップロードファイルをassets/images/backgroundに保存しても、サーバーからは見ていない。調べてみます。

**Comment by takumaki** [comment]
よく分かってないですが、ルーティング（routes.js）とかで何とかならないですかねー
