### ISSUE TITLE
ロギング機能の強化

### ISSUE THREAD

**Issue by takumaki** [ntechlab/KPT-board#9]
チケット作成時にチケットの内容をログ出力したい。
ログイン、ログアウト、チケット作成などすべての操作ログのヘッダに日時、ユーザID、DBキーを一律出力したい。
障害時のフォワードリカバリで困ったので。。

**Comment by tnog2014** [comment]
別なログライブラリ（例えば、log4js）を使ってログを出すのもよいですね。
log4jsだと、簡単に日付も出せるし、ファイル出力して、ログファイルのローテーションも可能です。
更に、ログ出力ラッパー関数を作って、ユーザIDなどの必要情報を出せるようにするとか。

**Comment by tnog2014** [comment]
Log4jを利用するようにしました。ユーザーidを一律表示しました。
